#!/usr/bin/env python3
"""Step 3b of the new full renorm: the topo-susceptibility alpha fit -> alpha_c
(one of two alpha methods; the other is the 1plaq vortex fit, step3a_1plaq.py).

At fixed (beta_c, beta1_c, alpha_eff_c) the coarse lattice scans `alpha`
(`alpha1 = alpha_eff_c - alpha`) on a RefVil lattice and matches the coarse
integer-winding susceptibility topo_sus(Q_s) onto the fine susceptibility scaled
by L**2. The fine component is Q_z (z-renorm) or Q_s (U-renorm).

Data is generated by CPN_observable_fit/measure_PP_Wil.main (which measures both
topo charge and conn_PP_corr), and the match + plots are done by
CPN_observable_fit/plot_topo_alpha.process_case_topo.

beta1_c is produced by step 2 as two estimates (magsus, corr); we run the coarse
alpha-scan at EACH beta1 (the fine sim is shared, since it depends only on the
fine model), giving alpha_c(topo) per beta1.

Sampler dispatch (per the pipeline spec):
  * coarse lattice : always RefVil (needs the integer s field for Q_s).
  * fine lattice   : RefVil if alpha_f != 0 OR renorm_type == "U"; otherwise
                     halfRefVil (pure-beta -> heatbath inside). U-renorm requires
                     alpha_f > 0 so the fine Q_s is well-defined.

Run as a subprocess with cwd=CPN_observable_fit.
"""

import os
import sys

# --- module-level path setup (see step1_2plaq.py for the spawn rationale) ----
_HERE = os.path.dirname(os.path.abspath(__file__))
_BASE = os.path.dirname(_HERE)
_SUBPROJECT = os.path.join(_BASE, "CPN_observable_fit")
if _SUBPROJECT not in sys.path:
    sys.path.insert(0, _SUBPROJECT)

import step_common  # noqa: E402  (imported after path setup)


def _topo_kwargs(topo):
    return dict(
        heatbath_fraction=topo["heatbath_fraction"],
        epsilon=topo["epsilon"], n_leapfrog=topo["n_leapfrog"],
        mass_a=topo["mass_a"], mass_z=topo["mass_z"],
        s_step=topo.get("s_step", 0.5), s_update_num=topo.get("s_update_num", 1),
        n_therm=topo["n_therm"], n_meas=topo["n_meas"],
        meas_interval=topo["meas_interval"],
        n_total=topo["n_total"], n_workers=topo["n_workers"],
    )


def run_step(cfg):
    from measure_PP_Wil import main as measure_main
    from plot_topo_alpha import process_case_topo, default_alpha_list

    N, mod, renorm_type = cfg["N"], cfg["mod"], cfg["renorm_type"]
    L, L_coarse = cfg["L"], cfg["L_coarse"]
    beta_f, beta1_f = cfg["beta_f"], cfg["beta1_f"]
    alpha_f, alpha1_f = cfg["alpha_f"], cfg["alpha1_f"]
    alpha_eff_f = cfg["alpha_eff_f"]
    beta_c = cfg["beta_c"]
    alpha_eff_c = cfg["alpha_eff_c"]
    beta1_c = cfg["beta1_c"]                       # {"magsus": ..., "corr": ...}
    alpha_list = [round(float(a), 3) for a in (cfg.get("alpha_list") or [])]
    if not alpha_list:
        # No explicit scan: auto-bracket around the 1plaq alpha_c (the topo alpha_c
        # should sit near it). Must happen BEFORE coarse data generation below.
        alpha_1plaq = cfg.get("alpha_1plaq")
        if alpha_1plaq is None or not (float(alpha_1plaq) > 0):
            raise RuntimeError(
                f"alpha_list is empty and no usable alpha_1plaq (got {alpha_1plaq!r}); "
                f"either provide alpha_list or ensure step 3a produced a positive alpha_c.")
        alpha_list = default_alpha_list(alpha_1plaq)
        print(f"[topo] alpha_list empty -> default from 1plaq alpha={alpha_1plaq:.4g}: "
              f"{alpha_list}")
    topo = cfg["topo"]
    mkw = _topo_kwargs(topo)

    L_f = L_coarse * L
    renorm = L

    # ---- Fine sampler dispatch (req 4) + guard for U-renorm -------------------
    if renorm_type == "U" and abs(alpha_f) < 1e-10:
        raise RuntimeError(
            f"U-renorm topo fit needs fine Q_s, but alpha_f={alpha_f}~=0 makes the "
            f"integer s field unconstrained (Q_s ill-defined). Use renorm_type='z', "
            f"or set alpha_f > 0."
        )
    fine_oft = "RefVil" if (renorm_type == "U" or abs(alpha_f) > 1e-10) else "halfRefVil"

    # ---- Fine topo sim: ONCE (shared across both beta1 values) ---------------
    # Empty argzz/wilson: topo needs only conn_PP_corr (always measured, for the
    # informational magsus/corr plots) + topo_charge. The fine file is reused via
    # measure_PP_Wil's top-up when fine_oft matches step 2's.
    print(f"[topo] fine   L={L_f} {fine_oft} beta={beta_f} beta1={beta1_f} "
          f"alpha={alpha_f} alpha1={alpha1_f}")
    measure_main(N, L_f, [(beta_f, beta1_f, alpha_f, alpha1_f)],
                 argzz_xy_list=[], wilson_xy_list=[],
                 mod=mod, obs_fit_type=fine_oft, **mkw)

    # ---- Coarse alpha-scan + topo match: per beta1 (magsus, corr) ------------
    # The per-method acc_rate/acc_rate_metro blocks live inside the
    # process_case_topo outputs stored in fit_details -- NOT duplicated at the
    # top level of the result dict.
    alpha_topo = {}
    fit_details = {}
    for b1_method in ("magsus", "corr"):
        b1c = beta1_c.get(b1_method)
        if b1c is None:
            print(f"[topo] beta1_c[{b1_method}] is None; skipping topo fit for it")
            alpha_topo[b1_method] = None
            fit_details[b1_method] = None
            continue

        coarse_list = [(beta_c, b1c, a, round(alpha_eff_c - a, 3)) for a in alpha_list]
        print(f"[topo] coarse L={L_coarse} RefVil beta={beta_c} beta1={b1c} "
              f"({len(alpha_list)} alpha points)")
        measure_main(N, L_coarse, coarse_list,
                     argzz_xy_list=[], wilson_xy_list=[],
                     mod=mod, obs_fit_type="RefVil", **mkw)

        info = dict(
            N=N, L_f=L_f, L_c=L_coarse, mod=mod, renorm=renorm, renorm_type=renorm_type,
            beta_f=beta_f, beta1_f=beta1_f, alpha_f=alpha_f, alpha1_f=alpha1_f,
            beta_c=beta_c, beta1_c=b1c, alpha_eff_c=alpha_eff_c,
            alpha_list=alpha_list, fine_obs_fit_type=fine_oft,
        )
        out = process_case_topo(info, mod=mod)
        if out is None:
            alpha_topo[b1_method] = None
            fit_details[b1_method] = None
            print(f"[topo] alpha_c[{b1_method}] = NO RESULT")
        else:
            alpha_topo[b1_method] = out.get("alpha_c")
            fit_details[b1_method] = out
            if out.get("alpha_c") is None:
                print(f"[topo] alpha_c[{b1_method}] = NO MATCH")
            else:
                print(f"[topo] alpha_c[{b1_method}] = {out['alpha_c']:.4f} "
                      f"(fine_target={out['fine_target']:.6g}, comp={out['fine_comp']})")

    return {
        "step": "topo_alpha",
        "renorm_type": renorm_type, "renorm": renorm, "L_f": L_f, "L_c": L_coarse,
        "N": N, "mod": mod,
        "beta_f": beta_f, "beta1_f": beta1_f,
        "alpha_f": alpha_f, "alpha1_f": alpha1_f, "alpha_eff_f": alpha_eff_f,
        "beta_c": beta_c, "alpha_eff_c": alpha_eff_c,
        "beta1_c_used": beta1_c,
        "alpha_list": alpha_list,
        "fine_obs_fit_type": fine_oft,
        "alpha_c": alpha_topo,                       # {"magsus": ..., "corr": ...}
        "fit_details": fit_details,                  # per-method process_case_topo
                                                     # outputs (carry acc_rate/_metro)
    }


if __name__ == "__main__":
    cfg = step_common.load_json(sys.argv[1])
    os.chdir(_SUBPROJECT)
    result = run_step(cfg)
    step_common.dump_json(result, cfg["_result_path"])
    a = result['alpha_c']
    print(f"[topo] alpha_c(topo) magsus={a['magsus']} corr={a['corr']}")
